import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LinkEntry from "../components/LinkEntry"
// @ts-ignore
import {links, name} from "/config.json"

const Home: NextPage = () => {
  return (
      <div className={styles.container + " bg-[#302C2C]"}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
        </Head>

        <main className={styles.main + " gap-[20px]"}>
          <div className="text-3xl">
            {name}
          </div>
          {links.map(LinkEntry)}
        </main>
      </div>
  )
}

export default Home
