import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LinkEntry from "../components/LinkEntry"

const Home: NextPage = () => {
  return (
      <div className={styles.container + " bg-[#302C2C]"}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
        </Head>

        <main className={styles.main + " gap-[20px]"}>
          <div className="text-3xl">
            John Smith
          </div>
          {
            [
              {
                name: "Website",
                link: "https://gdsc.nz",
                icon: "fa fa-globe",
              },
              {
                name: "Email",
                link: "mailto:hello@gdsc.nz",
                icon: "fa-regular fa-envelope",
              },
              {
                name: "GitHub",
                link: "https://github.com",
                icon: "fa-brands fa-github"
              },
              {
                name: "LinkedIn",
                link: "https://linkedin.com",
                icon: "fa-brands fa-linkedin"
              },
            ].map(LinkEntry)
          }
        </main>
      </div>
  )
}

export default Home
